### ISSUE TITLE
Won't enable in PHPStorm

### ISSUE THREAD

**Issue by hartman** [drewmutt/puggle#5]
Debug log shows:

Plugin 'Puggle' can't be loaded because: Plugin does not include any module dependency tags in its plugin.xml therefore is assumed legacy and can be loaded only in IntelliJ IDEA.

http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/plugin_compatibility.html

**Comment by Yoshi24517** [comment]
It's only supposed to be used in IntelliJ IDEA.

**Comment by drewmutt** [comment]
I don't see any reason why it couldn't be used in PHP storm.. other than the plugin.xml restriction. I'm looking into it now.

**Comment by drewmutt** [comment]
@hartman Done as per 0.8a release.

**Comment by hartman** [comment]
👍🏼
