### ISSUE TITLE
Auto brackets issue

### ISSUE THREAD

**Issue by dracconi** [drewmutt/puggle#7]
When typing `[[` or `{{` it's completed into `[[]]]` or `{{}}}` .

**Comment by Yoshi24517** [comment]
May I ask what your username is?

Being fixed by drewmutt.

**Comment by dracconi** [comment]
Iam not really written there, but here you have it `Desperek`

**Comment by Yoshi24517** [comment]
Yes, Thank You. drewmutt is working on a solution, and should have a patch out soon.

**Comment by drewmutt** [comment]
Fixed in v0.14a
